# Week 1 - NumPy
Go through the relevant parts of the NumPy documentation.

Focus only on:
- arrays
- shapes
- indexing/slicing
- broadcasting
- vectorization
- matrix multiplication
- aggregations
- random numbers

In [2]:
import numpy as np

## Basics

### Array creation

An array in NumPy is called an ndarray and is multidimensional.
`ndarray` has the following attributes:
- `ndim`: the number of axes/dimensions
- `shape`: the dimensions of the array in a tuple (n,m). The length of the shape tuple is thus `ndim`.
- `size`: the total number of elements in the array. This is equal to the product of the `shape` dimensions.
- `dtype`: the type of the elements in the array. This can be created/specified using standard Python types or NumPy types (int32, float64, complex32, etc.)
- `itemsize`: the size in bytes of each element in the array. So with `dytpe=float64`, `itemsize` will be 64/8=8 bytes. Equivalent to `dytpe.itemsize`.
- `data`: the buffer with the actual elements of the array. However, you typically just access the elements through indexing.

In [3]:
a = np.arange(15).reshape(3,5) # arange(n) creates 1D array consisting of [0-n)
print(f"a = \n{a}")
print(f"shape: {a.shape}")
print(f"ndim: {a.ndim}")
print(f"name: {a.dtype.name}")
print(f"itemsize: {a.itemsize}")
print(f"size: {a.size}")
print(f"type: {type(a)}")

a = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape: (3, 5)
ndim: 2
name: int64
itemsize: 8
size: 15
type: <class 'numpy.ndarray'>


In [4]:
# You can also just pass in a regular Python list or tuple into `array()`
a = np.array([2,3,4])
print(f"a = \n{a}")

# `array()` also transforms sequences of sequences (of sequences etc.) into dimensional arrays
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(f"b = \n{b}")

# Types if inferred, but can be specified
c = np.array([[1, 2], [3, 4]], dtype=np.complex128)
print(f"c = \n{c}")

a = 
[2 3 4]
b = 
[[1.5 2.  3. ]
 [4.  5.  6. ]]
c = 
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [5]:
# Often you know the size of the array, but not the contents. To initialize with placeholder values, you can use:
# Initialize with zeros
print(f"zeros\n {np.zeros((3,4))}")
# Initialize with ones (this creates, two 3x4 arrays) with specific type. Default is float64
print(f"\n ones\n {np.ones((2,3,4), dtype=np.int16)}")
# Random values
print(f"\n empty\n {np.empty((2,3))}")

zeros
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 ones
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

 empty
 [[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [6]:
# `arange`` creates a sequence of numbers
print(np.arange(15)) # make just a sequential list from 0-n
print(np.arange(10, 30, 5)) # make sequence from a-b jumping by c
print(np.arange(0, 2, 0.3)) # it even accepts FP arguments

# do note that due to FP error, you can run into issues with the number of elements, so it's better to use `linspace`
print(np.linspace(0, 2, 9)) # go from 0-2 with 9 elements
x = np.linspace(0, 2*np.pi, 100) # useful to evaluate lots of points
print(np.sin(x))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 

### Basic Operations

In [7]:
# Arithmetic ops on arrays apply *elementwise*. A new array is created and filled with the result.
a = np.array([20, 30, 40, 50])
b = np.array([0, 1, 2, 3])
c =  a - b
print(c)
d = b**2
print(d)
print(10 * np.sin(a))
print(a < 35)

# The product op * also applies elementwise. This is Hadamard/entrywise product, NOT dot product!
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A * B )

# To do dot product, use @ operator or `dot()`
print("\nDot product")
print(A @ B)
print(A.dot(B))

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[[2 0]
 [0 4]]

Dot product
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [8]:
# You can apply some operations like += and *= to modify an existing array rather than making a new one
print("\n")
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=np.int_)
b = rg.random((2, 3))
a *= 3
print(a)
b += a
print(b)
# a += b # ERROR!

# When operating with arrays of different types, the type of the resulting array corresponds
# to the more general or precise one (upcast)
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
print(b.dtype.name)
c = a + b
print(c)
print(c.dtype.name)
d = np.exp(c * 1j)
print(d)
print(d.dtype.name)




[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]
float64
[1.         2.57079633 4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [9]:
# Many unary ops like element sum array implemented as methods of the `ndarray` class
a = rg.random((2, 3))
print(a)
print(f"sum = {a.sum()}")
print(f"min = {a.min()}")
print(f"max = {a.max()}")

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
sum = 3.1057109529998157
min = 0.027559113243068367
max = 0.8277025938204418


In [10]:
# By default, these ops apply to the array like it's a list of numbers
# You can specify the `axis` parameter to apply an op along a specific axis
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0)) # sum of each column
print(b.min(axis=1)) # min of each row
print(b.cumsum(axis=1)) # cumulative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


### Universal functions

In [11]:
# NumPy has familiar functions like sin, cos, exp, which are called "universal functions" (`ufunc`)
# These operate elementwise on an array and produce an array as output.
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))
C = np.array([2., -1., 4.])
print(np.add(B,C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


### Indexing, slicing, and iterating

In [12]:
# 1D arrays can be indexed, sliced, and iterated over like lists and other Pythons sequences
a = np.arange(10)**3
print(a)
print(a[2]) # third element
print(a[2:5]) # third to fifth element
a[:6:2] = 1000
print(a)
print(a[::-1]) # reversed
for i in a:
    print(i**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]
[ 729  512  343  216  125 1000   27 1000    1 1000]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [13]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple
def f(x,y):
    return 10 * x + y
b = np.fromfunction(f, (5,4), dtype=np.int_)
print(b)
print(b[2,3]) # (row, col)
print(b[0:5, 1]) # each row in the second column
print(b[:, 1]) # same as previous
print(b[1:3, :]) # each column in the second and third row
# When fewer indices are provided than the number of axes, the missing indices are considered complete slices `:`
print(b[-1]) # the last row, equivalent to b[-1, :]
print("\n")

# The expression `b[i]` is treated as an `i` followed by as many instances of `:` as
# needed to represent the remaining axis.
# You can also write this using dots as `b[i, ...]` which is used to produce as many colons as needed
# for a  complete indexing tuple.
# e.g. for 5 axes, x[1, 2, ...] is equal to x[1, 2, :, :, :] 
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
print(c.shape)
print(c[1, ...]) # same as c[1, :, :] or c[1]
print(c[..., 2]) # same as c[:, :, 2]
print("\n")

# Iterating over multidimension arrays is done with respect to the first axis
for row in b:
    print(row)
# But if you want to perform an operation on each element in the array, you can use `.flat` which is an iterator
for element in b.flat:
    print(element)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Shape manipulation

### Changing the shape of an array

In [14]:
# The shape of an array can be changed with various commands.
a = np.floor(10*rg.random((3,4)))
print(f"A = \n{a}")

# The following three commands return a modified array, but do not change the original array.
print(f"Flattened = \n{a.ravel()}") # flattened array
print(f"Reshaped = \n{a.reshape(6,2)}") # modify the shape
print(f"Transposed = \n{a.T}") # transpose array
print(f"{a.shape} vs {a.T.shape}")

# If a dimension is given as -1 in a reshaping operation, the other dimensions are auto calculated
print(f"-1 reshape = \n{a.reshape(3, -1)}")

A = 
[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]
Flattened = 
[3. 7. 3. 4. 1. 4. 2. 2. 7. 2. 4. 9.]
Reshaped = 
[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]
 [7. 2.]
 [4. 9.]]
Transposed = 
[[3. 1. 7.]
 [7. 4. 2.]
 [3. 2. 4.]
 [4. 2. 9.]]
(3, 4) vs (4, 3)
-1 reshape = 
[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]


### Stacking together different arrays

In [15]:
# You can stack arrays along different axes
a = np.floor(10 * rg.random((2, 2)))
print(a)
b = np.floor(10 * rg.random((2, 2)))
print(b)
print(f"vstack = \n{np.vstack((a,b))}")
print(f"hstack = \n{np.hstack((a,b))}")

# There's also `column_stack` which stacks 1D arrays as columns into a 2D array. It's like `hstack` only for 2D arrays
from numpy import newaxis
print(f"column_stack = \n{np.column_stack((a,b))}") # with 2d arrays
print()
a = np.array([4., 2.])
b = np.array([3., 8.])
print(f"column_stack = \n{np.column_stack((a,b))}") # Returns a 2D array
print(f"hstack = \n{np.hstack((a,b))}") # see how this is different
print()

print(a[:, newaxis]) # transform a from an array to a 2D column vector
print(np.column_stack((a[:, newaxis], b[:, newaxis])))
print(np.hstack((a[:, newaxis], b[:, newaxis]))) # equivalent result


[[9. 7.]
 [5. 2.]]
[[1. 9.]
 [5. 1.]]
vstack = 
[[9. 7.]
 [5. 2.]
 [1. 9.]
 [5. 1.]]
hstack = 
[[9. 7. 1. 9.]
 [5. 2. 5. 1.]]
column_stack = 
[[9. 7. 1. 9.]
 [5. 2. 5. 1.]]

column_stack = 
[[4. 3.]
 [2. 8.]]
hstack = 
[4. 2. 3. 8.]

[[4.]
 [2.]]
[[4. 3.]
 [2. 8.]]
[[4. 3.]
 [2. 8.]]


### Splitting one array into several smaller ones

In [16]:
# You can use `hsplit`, `vsplit`, and `arraysplit`
a = np.floor(10 * rg.random((2, 12)))
print(a)
print(np.hsplit(a, 3))
print(np.hsplit(a, (3, 4)))
print(np.vsplit(a, 2))

[[6. 7. 6. 9. 0. 5. 4. 0. 6. 8. 5. 2.]
 [8. 5. 5. 7. 1. 8. 6. 7. 1. 8. 1. 0.]]
[array([[6., 7., 6., 9.],
       [8., 5., 5., 7.]]), array([[0., 5., 4., 0.],
       [1., 8., 6., 7.]]), array([[6., 8., 5., 2.],
       [1., 8., 1., 0.]])]
[array([[6., 7., 6.],
       [8., 5., 5.]]), array([[9.],
       [7.]]), array([[0., 5., 4., 0., 6., 8., 5., 2.],
       [1., 8., 6., 7., 1., 8., 1., 0.]])]
[array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.]]), array([[8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])]


## Copies and views

### No copy at all

In [17]:
# Simple assignments make no copy of objects or their data
a = np.arange(15).reshape(3,5)
b = a   # no new object is created
        # a and b are two names for the same ndarray object
print(b is a) # True

# Python passes mutable objects as references, so function calls make no copy
def f(x):
    print(id(x))
print(id(a)) # same id
f(a)         # same id

True
4572817680
4572817680


### View or shallow copy

In [18]:
# Different array objects can share the same data
# `view()` creates a new array object that looks at the same data
c = a.view()
print(c is a) # False
print(c.base is a) # True?, c is a view of the data owned by `a`
                    # docs say True, but this outputs False?
                    # I think it's a little bit of a memory thing, cause it definitely is a view
print(c.flags.owndata) # False
print()

c = c.reshape(5, 3) # `a`'s shape doesn't change, reassigned `c`` is still a view of `a`
print(a.shape) # still (3,5)
c[0, 2] = 1234 # `a`'s data changes
print(a)
print(c)
print()

# Slicing an array returns a view of it
s = a[:, 1:3]
s[:] = 10 # `s[:]` is a view of `s`.
print(a)

False
False
False

(3, 5)
[[   0    1 1234    3    4]
 [   5    6    7    8    9]
 [  10   11   12   13   14]]
[[   0    1 1234]
 [   3    4    5]
 [   6    7    8]
 [   9   10   11]
 [  12   13   14]]

[[ 0 10 10  3  4]
 [ 5 10 10  8  9]
 [10 10 10 13 14]]


So essentially you can have two arrays with different shapes but sharing the same data. If you modify one of the arrays, the other array will also be modified.

### Deep copy

In [19]:
# `copy()` forces a deep copy
d = a.copy() # new array object
print(d is a) # False
print(d.base is a) # False
d[0, 0] = 9999
print(a) # Nothing is 9999
print(d)
print()

# Sometimes `copy()` should be called after slicing if the original array is not required anymore.
# e.g. suppose array A is a huge intermediate result and the final result B is only a small fraction of A,
# then a deep copy should be made when constructing B with slicing.
a = np.arange(int(1e8))
b = a[:100].copy()
del a # memory of a can be released
print(b)
# If you didn't do `copy()`, `a` is referenced by `b`b and will thus persist in memory even if you did `del a`

False
False
[[ 0 10 10  3  4]
 [ 5 10 10  8  9]
 [10 10 10 13 14]]
[[9999   10   10    3    4]
 [   5   10   10    8    9]
 [  10   10   10   13   14]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


### Functions and methods overview

Array creation
- `arange`, `array`, `copy`, `empty`, `empty_like`, `eye`, `fromfile`, `fromfunction`, `identity`, `linspace`, `logspace`, `mgrid`, `ogrid`, `ones`, `ones_like`, `r_`, `zeros`, `zeros_like`

Conversions
- `ndarray.astype`, `atleast_1d`, `atleast_2d`, `atleast_3d`, `mat`

Manipulation
- `array_split`, `column_stack`, `concatenate`, `diagonal`, `dsplit`, `dstack`, `hsplit`, `hstack`, `ndarray.item`, `newaxis`, `ravel`, `repeat`, `reshape`, `resize`, `squeeze`, `swapaxes`, `take`, `transpose`, `vsplit`, `vstack`

Questions
- `all`, `any`, `nonzero`, `where`

Ordering
- `argmax`, `argmin`, `argsort`, `max`, `min`, `ptp`, `searchsorted`, `sort`

Operations
- `choose`, `compress`, `cumprod`, `cumsum`, `inner`, `ndarray.fill`, `imag`, `prod`, `put`, `putmask`, `real`, `sum`

Basic statistics
- `cov`, `mean`, `std`, `var`

Basic linear algebra
- `cross`, `dot`, `outer`, `linalg.svd`, `vdot`

## Less basic

### Broadcasting rules

In [20]:
# Broadcasting allows universal functions to deal, in a meaningful way, with inputs that don't have exactly the same shape.
# 1) If all input arrays do not share the same number of dimensions, a "1" will be 
#     repeatedly prepended to the shapes of the similar arrays until all the arrays have the same number of dimensions.
# 2) Ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the 
#     largest shape along that dimension. 
#     The value of the array element is assumed to be the same along that dimension for the "broadcast" array.
# After application of these rules, the size of all arrays must match.

## Advanced indexing and index tricks
In addition to indexing by integers and slices, arrays can be indexed by arrays of integers and arrays of booleans.

### Indexing with arrays of indices

In [28]:
a = np.arange(12)**2 # first 12 square numbers
# [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144]
i = np.array([1, 1, 3, 8, 5]) # array of indices
print(a[i]) # the elements of `a` at the positions `i`
j = np.array([[3,4], [9,7]]) # bidimensional array of indices
print(a[j]) # same shape as `j`
print()

# When the indexed array `a` is multidimensional, a single array of indices refers to the first dimension.
palette = np.array([[0, 0, 0],         # black
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])  # white
image = np.array([[0, 1, 2, 0],  # each value corresponds to a color in the palette
                  [0, 3, 4, 0]])
print(palette[image]) # the (2, 4, 3) color image
print()

# We can also give indexes for more than one dimension. The arrays of indices for each dimension must have the same shape.
a = np.arange(12).reshape(3, 4)
print(a)
i = np.array([[0, 1],  # indices for the first dim of `a`
              [1, 2]])
j = np.array([[2, 1],  # indices for the second dim
              [3, 3]])
print(a[i, j])  # i and j must have equal shape
print(a[i, 2])
print(a[:, j])

[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]

[[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  5]
 [ 7 11]]
[[ 2  6]
 [ 6 10]]
[[[ 2  1]
  [ 3  3]]

 [[ 6  5]
  [ 7  7]]

 [[10  9]
  [11 11]]]


In [29]:
# In Python, `arr[i, j]` is exactly the same as arr[(i, j)], so we can put `i` and `j` in a tuple and then do indexing with that
l = (i,j)
print(a[l]) # equivalent to `a[i,j]`

# However, we can't do this by putting `i` and `j` into an array, because the array will be interpreted as indexing the dimension of `a``.
s = np.array([i,j]) # not what we want
# print(a[s]) # out of bounds error
print(a[tuple(s)]) # same as `a[i,j]`

[[ 2  5]
 [ 7 11]]
[[ 2  5]
 [ 7 11]]


In [30]:
# Another common use of indexing with arrays is the search of the max value of time-dependent series
time = np.linspace(20, 140, 5) # time scale
data = np.sin(np.arange(20)).reshape(5,4) # time-dependent series
print(time)
print(data)
# index of the maxima for each series
ind = data.argmax(axis=0)
print(ind)
# times corresponding to the maxima
time_max = time[ind]
data_max = data[ind, range(data.shape[1])] # data[ind[0], 0], data[ind[1], 1] ...
print(time_max)
print(data_max)
print(np.all(data_max == data.max(axis=0)))

[ 20.  50.  80. 110. 140.]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 80.  20. 110.  50.]
[0.98935825 0.84147098 0.99060736 0.6569866 ]
True


In [ ]:
# You can also use indexing with arrays as a target to assign to
a = np.arange(5)
print(a)
a[[1,3,4]] = 0
print(a)
print()
# However, when the list of indices contains repitions, the assignment is done several times, leaving behind the last value
a = np.arange(5)
a[[0, 0, 2]] = [1, 2, 3]
print(a)
print()
# This is reasonable, but watch out if you want to use `+=`, as it may not do what you expect
a = np.arange(5)
a[[0, 0, 2]] += 1
print(a)
# Even though 0 occurs twice in the list of indices, the 0th element is only incremented once.
# This is because Python requires `a += 1` to be equivalent to `a = a + 1`

[0 1 2 3 4]
[0 0 2 0 0]

[2 1 3 3 4]


### Indexing with boolean arrays

### The `ix_()` function

### Indexing with strings

## Tips and tricks

### "Automatic" reshaping

### Vector stacking

### Histograms