# Week 1 - NumPy
Go through the relevant parts of the NumPy documentation.

Focus only on:
- arrays
- shapes
- indexing/slicing
- broadcasting
- vectorization
- matrix multiplication
- aggregations
- random numbers

In [1]:
import numpy as np

An array in NumPy is called an ndarray and is multidimensional.
`ndarray` has the following attributes:
- `ndim`: the number of axes/dimensions
- `shape`: the dimensions of the array in a tuple (n,m). The length of the shape tuple is thus `ndim`.
- `size`: the total number of elements in the array. This is equal to the product of the `shape` dimensions.
- `dtype`: the type of the elements in the array. This can be created/specified using standard Python types or NumPy types (int32, float64, complex32, etc.)
- `itemsize`: the size in bytes of each element in the array. So with `dytpe=float64`, `itemsize` will be 64/8=8 bytes. Equivalent to `dytpe.itemsize`.
- `data`: the buffer with the actual elements of the array. However, you typically just access the elements through indexing.

In [18]:
a = np.arange(15).reshape(3,5) # arange(n) creates 1D array consisting of [0-n)
print(f"a = \n{a}")
print(f"shape: {a.shape}")
print(f"ndim: {a.ndim}")
print(f"name: {a.dtype.name}")
print(f"itemsize: {a.itemsize}")
print(f"size: {a.size}")
print(f"type: {type(a)}")

a = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape: (3, 5)
ndim: 2
name: int64
itemsize: 8
size: 15
type: <class 'numpy.ndarray'>


In [20]:
# You can also just pass in a regular Python list or tuple into `array()`
a = np.array([2,3,4])
print(f"a = \n{a}")

# `array()` also transforms sequences of sequences (of sequences etc.) into dimensional arrays
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(f"b = \n{b}")

# Types if inferred, but can be specified
c = np.array([[1, 2], [3, 4]], dtype=np.complex128)
print(f"c = \n{c}")

a = 
[2 3 4]
b = 
[[1.5 2.  3. ]
 [4.  5.  6. ]]
c = 
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [25]:
# Often you know the size of the array, but not the contents. To initialize with placeholder values, you can use:
# Initialize with zeros
print(f"zeros\n {np.zeros((3,4))}")
# Initialize with ones (this creates, two 3x4 arrays) with specific type. Default is float64
print(f"\n ones\n {np.ones((2,3,4), dtype=np.int16)}")
# Random values
print(f"\n empty\n {np.empty((2,3))}")

zeros
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 ones
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

 empty
 [[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [ ]:
# `arange`` creates a sequence of numbers
print(np.arange(15)) # make just a sequential list from 0-n
print(np.arange(10, 30, 5)) # make sequence from a-b jumping by c
print(np.arange(0, 2, 0.3)) # it even accepts FP arguments

# do note that due to FP error, you can run into issues with the number of elements, so it's better to use `linspace`
print(np.linspace(0, 2, 9)) # go from 0-2 with 9 elements
x = np.linspace(0, 2*np.pi, 100) # useful to evaluate lots of points
print(np.sin(x))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 